# Generated by Django 5.0.6 on 2024-07-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_staff', to='task.customuser'),
        ),
    ]
