# Generated by Django 5.0.6 on 2024-07-06 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task', '0004_alter_task_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('Заказачик', 'Customer'), ('Сотрудник', 'Staff')], max_length=15)),
                ('photo', models.ImageField(upload_to='media')),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит этот пользователь. Пользователь получит все разрешения, предоставленные каждой из его групп.', related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='группы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='специфические права для этого пользователя.', related_name='customuser_user_permissions', related_query_name='customuser', to='auth.permission', verbose_name='права пользователя')),
            ],
            options={
                'permissions': (('can_create', 'Может создавать задачи'), ('access_all_tasks', 'Доступ ко всем задачам'), ('can_add_customer', 'Может добавлять заказчика'), ('can_add_staff', 'Может добавлять сотрудника'), ('access_all_staff', 'Доступ ко всем сотрудникам')),
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_customer', to='task.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to='task.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_staff', to='task.profile'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
