# Generated by Django 5.0.6 on 2024-07-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_profile_alter_task_customer_alter_task_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Заказчик', 'Customer'), ('Сотрудник', 'Staff')], max_length=15),
        ),
    ]
